---
title: "Class 16: Downstream analysis and PCA"
author: "Suzanne Enos"
format: pdf
---

```{r}
library(BiocManager)
library(tximport)
```

```{r}
folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path( folders, "abundance.h5" )
names(files) <- samples

txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
```

```{r}
head(txi.kallisto$counts)
```

```{r}
colSums(txi.kallisto$counts)
```

```{r}
sum(rowSums(txi.kallisto$counts)>0)
```

```{r}
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]
```

```{r}
keep2 <- apply(kset.nonzero,1,sd)>0
x <- kset.nonzero[keep2,]
```

# PCA

```{r}
pca <- prcomp(t(x), scale = TRUE)
summary(pca)
```

# PLOT

```{r}
plot(pca$x[,1], pca$x[,2],
     col=c("blue", "blue", "red", "red"),
     xlab = "PC1", ylab="PC2", pch=16)
```

ggplot
```{r}
library(ggplot2)
library(ggrepel)
```

```{r}
colData <- data.frame(condition = factor(rep(c("control", "treatment"), each = 2)))
rownames(colData) <- colnames(txi.kallisto$counts)
```

```{r}
y <- as.data.frame(pca$x)
y$condition <- as.factor(colData$condition)
```

```{r}
ggplot(y) +
  aes(PC1, PC2, col = condition) + 
  geom_point() +
  geom_text_repel(label = rownames(y)) +
  theme_bw()
```

# Differential-expression analysis

```{r}
library(DESeq2)
```

```{r}
sampletable <- data.frame(condition = factor(rep(c("control", "treatment"), each = 2)))
rownames(sampletable) <- colnames(txi.kallisto$counts)
```

```{r}
dds <- DESeqDataSetFromTximport(txi.kallisto, sampletable, ~condition)
```

```{r}
dds <- DESeq(dds)
```

```{r}
res <- results(dds)
head(res)
```

